CONFIG_NAME: 'fonts'
dataset_name: 'fonts'
data_dir: '../data/fonts'

imsize: 256
z_dim: 100
cond_dim: 512
manual_seed: 100
cuda: True

clip4evl: {'src':"clip", 'type':'ViT-B/32'}
clip4trn: {'src':"clip", 'type':'ViT-B/32'} 
clip4text: {'src':"clip", 'type':'ViT-B/32'} 

stamp: 'normal'
state_epoch: 1
max_epoch: 1502
batch_size: 8
gpu_id: 0
nf: 64
ch_size: 3

scaler_min: 64
growth_interval: 2000
lr_g: 0.0001
lr_d: 0.0004
sim_w: 4.0

gen_interval: 5 #1
test_interval: 20 #5
save_interval: 20

sample_times: 12
npz_path: '../data/birds/npz/bird_val256_FIDK0.npz'
log_dir: 'new'
#model_save_file: 'C:\Users\rinat\PycharmProjects\gnlp-final\GALIP\code\saved_models\fonts\GALIP_nf64_normal_fonts_256_2023_04_10_20_51_54'
#img_save_dir: 'C:\Users\rinat\PycharmProjects\gnlp-final\GALIP\code\imgs/fonts\train\GALIP_nf64_normal_fonts_256_2023_04_10_20_51_54'
#log_dir: 'C:\Users\rinat\PycharmProjects\gnlp-final\GALIP\code\logs\fonts\train\GALIP_nf64_normal_fonts_256_2023_04_10_20_51_54'
